create table if not exists participant_location (
  location_id bigint generated by default as identity primary key,
  participant_id bigint not null references participant(participant_id) on delete cascade,
  place_name text,
  address text not null,
  latitude double precision not null,
  longitude double precision not null,
  return_address text,
  return_latitude double precision,
  return_longitude double precision
);

create table if not exists participant_preference (
  preference_id bigint generated by default as identity primary key,
  participant_id bigint not null references participant(participant_id) on delete cascade,
  preference_type text not null,
  preference_value text not null
);
